### ISSUE TITLE
Valid syntax odd numbers of double quotes mess up syntax coloring

### ISSUE THREAD

**Issue by donbarthel** [tralamazza/Sublime-OpenScad#7]
This line causes all succeeding lines to be colored yellow (like all succeeding lines were part of one continuous string:

`str((calc_feet == 0) ? "" : str(calc_feet, "'"), calc_inches, "\"", fraction_to_text(length_fraction));`

The problem seems to be `"\""` which is interpreted as mismatching quotes but it in fact an escaped quote.

![Screenshot from 2020-02-03 19-43-58](https://user-images.githubusercontent.com/5126455/73711989-8f96a800-46bd-11ea-928e-87ed931e2c05.png)

**Comment by tralamazza** [comment]
correct, the escape character is not supported. I will take a closer look, thanks

**Comment by tralamazza** [comment]
@donbarthel could you try again?
this seems to have fixed it https://github.com/tralamazza/Sublime-OpenScad/commit/546900805d705b2ad91bea0060e973f880d30d81
