### ISSUE TITLE
cylinder is not highlighted

### ISSUE THREAD

**Issue by aliktab** [tralamazza/Sublime-OpenScad#9]
![Screenshot 2021-03-13 at 22 41 08](https://user-images.githubusercontent.com/7151343/111047096-36b34a80-844d-11eb-99ae-460be94922fa.jpg)

**Comment by tralamazza** [comment]
Are you sure you have the latest version? `cylinder` works for me

**Comment by aliktab** [comment]
It works with the only this set os parameters: "cylinder(h=${1:1}, r=${2:1}, center=${3:false}, \$fn=${4:20});"
But it has more versions with two radiuses or with diameters.

**Comment by tralamazza** [comment]
![image](https://user-images.githubusercontent.com/132159/113018110-77ff6600-9180-11eb-84cf-2f49c31a217d.png)
```
cylinder($fn = 0, $fa = 12, $fs = 2, h = 1, r1 = 1, r2 = 1, center = false);
cylinder(h=15, r1=9.5, r2=19.5, center=false);
cylinder(  15,    9.5,    19.5, false);
cylinder(  15,    9.5,    19.5);
cylinder(  15,    9.5, d2=39  );
cylinder(  15, d1=19,  d2=39  );
cylinder(  15, d1=19,  r2=19.5);
cylinder(h=15, r1=10, r2=0, center=true);
cylinder(  15,    10,    0,        true);
cylinder(h=15, d1=20, d2=0, center=true);
cylinder(h=20, r=10, center=true);
cylinder(  20,   10, 10,true);
cylinder(  20, d=20, center=true);
cylinder(  20,r1=10, d2=20, center=true);
cylinder(  20,r1=10, d2=2*10, center=true);
```

**Comment by aliktab** [comment]
I've just updated and it's working now.
